### PR TITLE
Add log_in tag in navbar

### LINKED ISSUE #100: Add login tag
log in tag was missing and i have added it in order to have login signup tags on the main page for not logged in users.

### PR DESCRIPTION
**Pull request by thetaxas2468**
in this commit log in tag was missing and i have added it in order to have login signup tags on the main page for not logged in users.

- closes #100

### CODE REVIEW

**Comment by thetaxas2468** [comment]
tag

**Comment by pazMenachem** [comment]
why not adding the url for the login page? the template already exists.

**Comment by thetaxas2468** [comment]
> why not adding the url for the login page? the template already exists.

I dont understand

**Comment by pazMenachem** [comment]
> > why not adding the url for the login page? the template already exists.
> 
> I dont understand

nvm didnt notice the href.👍

**Comment by MeitarRizner** [comment]
LGTM

**Review by yftacherzog — APPROVED** [review]

**Review by nofaralfasi — APPROVED** [review]

**Pull request merged**
