### PR TITLE
Add links to linkedIn

### PR DESCRIPTION
**Pull request by LiorSilberman**
Add links to our linkedin accounts in the description page.

wait for Paz and Rawan urls account.

### CODE REVIEW

**Comment by yftacherzog** [comment]
@LiorSilberman something is broken with the commit. I think it somehow includes a previous commit as well.

**Comment by LiorSilberman** [comment]
> @LiorSilberman something is broken with the commit. I think it somehow includes a previous commit as well.

ok that's weird i will try to add it again

**Comment by yftacherzog** [comment]
> > @LiorSilberman something is broken with the commit. I think it somehow includes a previous commit as well.
> 
> ok that's weird i will try to add it again

Might be that you accidentally used `git commit --amend`.

**Comment by thetaxas2468** [comment]
> > > @LiorSilberman something is broken with the commit. I think it somehow includes a previous commit as well.
> > 
> > 
> > ok that's weird i will try to add it again
> 
> Might be that you accidentally used `git commit --amend`.

Can you explain what is wrong,because i see that there is a 1 commit  its 1 commit behind the main

**Comment by yftacherzog** [comment]
> > > > @LiorSilberman something is broken with the commit. I think it somehow includes a previous commit as well.
> > > 
> > > 
> > > ok that's weird i will try to add it again
> > 
> > 
> > Might be that you accidentally used `git commit --amend`.
> 
> Can you explain what is wrong,because i see that there is a 1 commit its 1 commit behind the main

It says authored by etc. It looks like the merge-commit of the last thing that was merged.

image

Also, if you scroll down to the bottom of the changes page, you'll see this:

image

Clicking on it, you'd see some unrelated changes.

**Comment by thetaxas2468** [comment]
> > > > > @LiorSilberman something is broken with the commit. I think it somehow includes a previous commit as well.
> > > > 
> > > > 
> > > > ok that's weird i will try to add it again
> > > 
> > > 
> > > Might be that you accidentally used `git commit --amend`.
> > 
> > 
> > Can you explain what is wrong,because i see that there is a 1 commit its 1 commit behind the main
> 
> It says authored and etc. It looks like it contains the merge-commit of the last thing that was merged.
> 
> image
> 
> Also, if you scroll down to the bottom of the changes page, you'll see this:
> 
> image
> 
> Clicking on it, you'd see some unrelated changes.

Understood thanks!

**Pull request closed without merging**
