### PR TITLE
Add logout

### LINKED ISSUE #98: Add logout
i have added logging out functionality so if you are logged in you can log out but if you are logged out you will not be able to log out.

### PR DESCRIPTION
**Pull request by thetaxas2468**
in this commit i have added logging out functionality so if you are logged in you can log out but if you are logged out you will not be able to log out.

- closes #98

### CODE REVIEW

**Comment by thetaxas2468** [comment]
logged_out
logged_in

**Comment by pazMenachem** [comment]
LGTM👍

**Comment by MeitarRizner** [comment]
LGTM

**Review by yftacherzog — APPROVED** [review]

**Comment by nofaralfasi** [comment]
Do you think we should also have a test for client logout? 
Other than that, LGTM.

**Review by nofaralfasi — APPROVED** [review]

**Pull request merged**
