### PR TITLE
Add DFD for our app

### PR DESCRIPTION
**Pull request by LiorSilberman**
We Create DFD file for our app.
Here you can see the functionality of the app.

### CODE REVIEW

**Comment by Omeramsc** [comment]
PR missing a description and a link to an issue.

**Comment by pazMenachem** [comment]
lior you can modify the description by clicking on the pull request -> right next to code you have edit button.

**Review by pazMenachem — CHANGES_REQUESTED** [review]
lior you can modify the description by clicking on the pull request -> right next to code you have edit button.

**Comment by thetaxas2468** [comment]
You can do that by commit --amend and add your description i guess,other than that it looks good

**Review by Omeramsc — CHANGES_REQUESTED** [review]
DFD usually have 3 sections (lanes): 
1. Users/Players/entities
2. Actions 
3. Users/Players/entities

and the arrows between those sections, with the information passed with them. 

I'd expect to see `Client` twice, or more, rather than have an action (aka login) on the same section. 

also, for example, "filter" seems like a functionality, not an information. it can have a circle as well (you're not limited to one circle AFAIR)

**Comment by Omeramsc** [comment]
Any updates about that? the fact that the demo passed doesn't mean we don't need this done.

**Comment by pazMenachem** [comment]
> Any updates about that? the fact that the demo passed doesn't mean we don't need this done.
we will work on it shortly

**Comment by LiorSilberman** [comment]
> Any updates about that? the fact that the demo passed doesn't mean we don't need this done.
I added now the new DFD file after changes.

**Comment by pazMenachem** [comment]
@Omeramsc updated.

**Review by Omeramsc — APPROVED** [review]
LGTM

**Pull request merged**
