### PR TITLE
Add links to LinkedIn

### LINKED ISSUE #107: Add links to our linkedIn accounts
In this PR I update our description page with links to our linkedIn accounts.
#106

### PR DESCRIPTION
**Pull request by LiorSilberman**
Add links to our linkedin accounts in the description page.

wait for Paz and Rawan urls account.

image:
links

fixed #107

### CODE REVIEW

**Review by yftacherzog — APPROVED** [review]
If it doesn't get to merge before the demo, and you'd like to have it merged afterwards then we can do that as well.

**Review by thetaxas2468 — APPROVED** [review]
Create issue for this PR and other than that LGTM!

**Comment by Omeramsc** [comment]
Nice idea, please ping us when all the links are active.

**Comment by LiorSilberman** [comment]
> Nice idea, please ping us when all the links are active.

All the links are active and work

**Pull request merged**
